name: p_chat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.3.1
  flutter_spinkit: ^5.2.1
  flutter_riverpod: ^2.5.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1
  pinput: ^5.0.0
  http: ^1.3.0
  animated_text_kit: ^4.2.3
  grouped_list: ^6.0.0
  file_picker: ^10.2.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  url_launcher: ^6.3.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: Inter-VariableFont_opsz,wght.ttf
      fonts:
        - asset: font/Inter-VariableFont_opsz,wght.ttf
        # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
